kind: ConfigMap
metadata:
  name: {{.Chart.Name}}-{{.Values.global.targetNamespace}}-{{lower .Values.global.branch}}-kubeconfig
  labels:
    name: {{.Chart.Name}}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: {{.Chart.Name}}
    costcentre: PBS
apiVersion: v1
data:
  config: |-
    apiVersion: v1
    kind: Config
    contexts:
    - name: "ops-kops1"
      context:
        cluster: "ops-kops1"
        user: "ops-kops1"
    current-context: "ops-kops1"
    clusters:
    - name: "ops-kops1"
      cluster:
        api-version: v1
        server: "https://kops1.service.ops.iptho.co.uk"
        insecure-skip-tls-verify: true
    users:  
      - name: "ops-kops1"
        user:
          token: {{.Values.global.kubeOpsToken | quote}}
