
package uk.gov.ho.domain.component.api.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NotificationService", targetNamespace = "http://pbs.pidp.fujitsu.bia.homeoffice.gov.uk/notification/newsponsorapplication/", wsdlLocation = "https://metastorm-dev-i-spon-pbs.service.np.iptho.co.uk/BPMServices/BPMService.asmx?wsdl")
public class NotificationService
    extends Service
{

    private final static URL NOTIFICATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException NOTIFICATIONSERVICE_EXCEPTION;
    private final static QName NOTIFICATIONSERVICE_QNAME = new QName("http://pbs.pidp.fujitsu.bia.homeoffice.gov.uk/notification/newsponsorapplication/", "NotificationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://metastorm-dev-i-spon-pbs.service.np.iptho.co.uk/BPMServices/BPMService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTIFICATIONSERVICE_WSDL_LOCATION = url;
        NOTIFICATIONSERVICE_EXCEPTION = e;
    }

    public NotificationService() {
        super(__getWsdlLocation(), NOTIFICATIONSERVICE_QNAME);
    }

    public NotificationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTIFICATIONSERVICE_QNAME, features);
    }

    public NotificationService(URL wsdlLocation) {
        super(wsdlLocation, NOTIFICATIONSERVICE_QNAME);
    }

    public NotificationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTIFICATIONSERVICE_QNAME, features);
    }

    public NotificationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NotificationServiceSoap
     */
    @WebEndpoint(name = "NotificationServiceSoap")
    public NotificationServiceSoap getNotificationServiceSoap() {
        return super.getPort(new QName("http://pbs.pidp.fujitsu.bia.homeoffice.gov.uk/notification/newsponsorapplication/", "NotificationServiceSoap"), NotificationServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificationServiceSoap
     */
    @WebEndpoint(name = "NotificationServiceSoap")
    public NotificationServiceSoap getNotificationServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://pbs.pidp.fujitsu.bia.homeoffice.gov.uk/notification/newsponsorapplication/", "NotificationServiceSoap"), NotificationServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTIFICATIONSERVICE_EXCEPTION!= null) {
            throw NOTIFICATIONSERVICE_EXCEPTION;
        }
        return NOTIFICATIONSERVICE_WSDL_LOCATION;
    }

}
