
package uk.gov.ho.domain.component.api.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotificationServiceSoap", targetNamespace = "http://pbs.pidp.fujitsu.bia.homeoffice.gov.uk/notification/newsponsorapplication/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotificationServiceSoap {


    /**
     * 
     * @param sponsorApplicationURN
     * @return
     *     returns uk.gov.ho.domain.component.api.soap.PBSWebServiceError
     */
    @WebMethod(operationName = "NewSponsorApplication", action = "http://pbs.pidp.fujitsu.bia.homeoffice.gov.uk/notification/newsponsorapplication/NewSponsorApplication")
    @WebResult(name = "NewSponsorApplicationResult", targetNamespace = "http://pbs.pidp.fujitsu.bia.homeoffice.gov.uk/notification/newsponsorapplication/")
    @RequestWrapper(localName = "NewSponsorApplication", targetNamespace = "http://pbs.pidp.fujitsu.bia.homeoffice.gov.uk/notification/newsponsorapplication/", className = "uk.gov.ho.domain.component.api.soap.NewSponsorApplication")
    @ResponseWrapper(localName = "NewSponsorApplicationResponse", targetNamespace = "http://pbs.pidp.fujitsu.bia.homeoffice.gov.uk/notification/newsponsorapplication/", className = "uk.gov.ho.domain.component.api.soap.NewSponsorApplicationResponse")
    public PBSWebServiceError newSponsorApplication(
        @WebParam(name = "SponsorApplicationURN", targetNamespace = "http://pbs.pidp.fujitsu.bia.homeoffice.gov.uk/notification/newsponsorapplication/")
        String sponsorApplicationURN);

    /**
     * 
     * @param sponsorApplicationURN
     * @return
     *     returns uk.gov.ho.domain.component.api.soap.PBSWebServiceError
     */
    @WebMethod(operationName = "LinkToExistingApplication", action = "http://pbs.pidp.fujitsu.bia.homeoffice.gov.uk/notification/newsponsorapplication/LinkToExistingApplication")
    @WebResult(name = "LinkToExistingApplicationResult", targetNamespace = "http://pbs.pidp.fujitsu.bia.homeoffice.gov.uk/notification/newsponsorapplication/")
    @RequestWrapper(localName = "LinkToExistingApplication", targetNamespace = "http://pbs.pidp.fujitsu.bia.homeoffice.gov.uk/notification/newsponsorapplication/", className = "uk.gov.ho.domain.component.api.soap.LinkToExistingApplication")
    @ResponseWrapper(localName = "LinkToExistingApplicationResponse", targetNamespace = "http://pbs.pidp.fujitsu.bia.homeoffice.gov.uk/notification/newsponsorapplication/", className = "uk.gov.ho.domain.component.api.soap.LinkToExistingApplicationResponse")
    public PBSWebServiceError linkToExistingApplication(
        @WebParam(name = "SponsorApplicationURN", targetNamespace = "http://pbs.pidp.fujitsu.bia.homeoffice.gov.uk/notification/newsponsorapplication/")
        String sponsorApplicationURN);

}
